# Generated by Django 4.2 on 2023-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odevlib", "0002_added_request_logger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlogentry",
            name="application",
            field=models.TextField(verbose_name="Application name"),
        ),
        migrations.AlterField(
            model_name="requestlogentry",
            name="method",
            field=models.TextField(verbose_name="HTTP method"),
        ),
        migrations.AlterField(
            model_name="requestlogentry",
            name="path",
            field=models.TextField(verbose_name="HTTP path"),
        ),
    ]
