from . import filters as filters, filterset as filterset
from .. import compat as compat, utils as utils
from _typeshed import Incomplete
from django.utils.deprecation import RenameMethodsBase

class RenameAttributes(utils.RenameAttributesBase, RenameMethodsBase):
    renamed_attributes: Incomplete
    renamed_methods: Incomplete

class DjangoFilterBackend(metaclass=RenameAttributes):
    filterset_base: Incomplete
    raise_exception: bool
    @property
    def template(self): ...
    def get_filterset(self, request, queryset, view): ...
    def get_filterset_class(self, view, queryset: Incomplete | None = ...): ...
    def get_filterset_kwargs(self, request, queryset, view): ...
    def filter_queryset(self, request, queryset, view): ...
    def to_html(self, request, queryset, view): ...
    def get_coreschema_field(self, field): ...
    def get_schema_fields(self, view): ...
    def get_schema_operation_parameters(self, view): ...
