FROM python:3.11

WORKDIR /app

RUN apt update && \
    apt install -y postgresql postgresql-contrib && \
    pip install poetry && \
    poetry config virtualenvs.create false
COPY poetry.lock pyproject.toml ./
RUN poetry install

COPY . .

RUN cd docs && make build


FROM nginx:1.14-alpine

WORKDIR /app

RUN rm -rf /etc/nginx/conf.d
COPY ci/nginx.conf /etc/nginx/nginx.conf

# Copy build dist files to NGINX image
COPY --from=0 /app/docs/build/html /app
