FROM python:3.11

WORKDIR /app

RUN apt update && \
    apt install -y postgresql postgresql-contrib && \
    pip install poetry && \
    poetry config virtualenvs.create false
COPY poetry.lock pyproject.toml ./
RUN poetry install

COPY . .

CMD sh ci/entrypoint.sh
