from . import utils as utils
from _typeshed import Incomplete
from django.contrib import admin

USER_NATURAL_KEY: Incomplete
SIMPLE_HISTORY_EDIT: Incomplete

class SimpleHistoryAdmin(admin.ModelAdmin):
    object_history_template: str
    object_history_form_template: str
    def get_urls(self): ...
    def history_view(self, request, object_id, extra_context: Incomplete | None = ...): ...
    def history_view_title(self, obj): ...
    def response_change(self, request, obj): ...
    def history_form_view(self, request, object_id, version_id, extra_context: Incomplete | None = ...): ...
    def history_form_view_title(self, obj): ...
    def render_history_view(self, request, template, context, **kwargs): ...
    def save_model(self, request, obj, form, change) -> None: ...
    @property
    def content_type_model_cls(self): ...
    @property
    def revert_disabled(self): ...
